name: Crates IO

on:
  workflow_dispatch:
    inputs:
      publish:
        description: "If publish packages"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: "ACTIONS: Checkout"
        uses: actions/checkout@v4

      - name: "Install: Rust toolchain"
        uses: dsherret/rust-toolchain-file@v1

      - name: "Check packages"
        if: ${{ !inputs.publish }}
        run: cargo publish --dry-run

      - name: "Publish packages"
        if: ${{ inputs.publish }}
        run: cargo publish
