name: Docs

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "ACTIONS: Checkout"
        uses: actions/checkout@v4

      - name: "Install: Rust toolchain"
        uses: dsherret/rust-toolchain-file@v1

      - name: "ACTIONS: Setup caching"
        uses: Swatinem/rust-cache@v2

      - name: "Test: Doc examples"
        if: github.event_name == 'pull_request'
        run: cargo test --doc
