name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "ACTIONS: Checkout"
        uses: actions/checkout@v4

      - name: "Install: Rust toolchain"
        uses: dsherret/rust-toolchain-file@v1

      - name: "ACTIONS: Setup caching"
        uses: Swatinem/rust-cache@v2

      - name: "Test: Doc examples"
        if: github.event_name == 'pull_request'
        run: cargo test --doc

      - name: "Build: Docs"
        env:
          RUSTDOCFLAGS: --enable-index-page -Zunstable-options
        run: |
          cargo doc --no-deps --workspace
          rm -f target/doc/.lock

      - name: "ACTIONS: Setup GitHub Pages"
        if: github.event_name == 'push'
        uses: actions/configure-pages@v4

      - name: "ACTIONS: Upload Pages artifact"
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

      - name: "ACTIONS: Deploy to GitHub Pages"
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4
